### ISSUE TITLE
"Generate:Rendering" translation key does not work

### ISSUE THREAD

**Issue by RLH-2110** [KiwifruitDev/NonsensicalVideoGenerator#10]
### Release

Steam Release

### Version

1.0.11

### Platform

Windows

### Severity

Cosmetic

### Description

The translation key for "Rendering is in progress." does not work

### Reproduction Steps

I provided a test translation file, load it and render a video, notice the text is unchanged.

https://pastebin.com/zVeFQJ6i

### Expected Behavior

the new text will be used

### Actual Behavior

the original English text is used

### Screenshots

https://imgur.com/a/Hr1wDhc

### Proton Version

- [ ] Ge-Proton7-30
- [ ] Proton Experimental
- [ ] Proton 8.0-3
- [ ] Proton 7.0-6
- [ ] Proton 6.3-8
- [ ] Proton 5.13-6
- [ ] Proton 5.0-10
- [ ] Proton 4.11-13
- [ ] Proton 4.2-9
- [ ] Proton 3.16-9
- [ ] Proton 3.7-8
- [ ] Proton Hotfix

**Comment by KiwifruitDev** [comment]
Fixed with f9fefa8 ([v1.0.1.2](https://store.steampowered.com/news/app/2516360/view/4250916799096006721)).
