### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by xzh3r** [KiwifruitDev/NonsensicalVideoGenerator#2]
### Severity

Critical

### Description

At least on my OS, it does not run via Proton

### Benefits

Wider userbase by supporting more operating systems

**Comment by KiwifruitDev** [comment]
Milestone 2 Hotfix 2 (v1.0.0.8) now includes a DesktopGL beta.
https://store.steampowered.com/news/app/2516360/view/3690188204953453351?l=english
Proton should play a lot nicer with it, please try it out when you have a chance.

**Comment by antho27** [comment]
I think this is aslo "steam deck port"?

**Comment by KiwifruitDev** [comment]
I stopped production of the DesktopGL port because usage data showed that nobody was using it at the time. If there is any further interest, I will reconsider.

**Comment by KiwifruitDev** [comment]
NVG is not planned to support Linux due to increasing issues with Proton and MonoGame's general lackluster support for it.
