### ISSUE TITLE
Not detecting dependencies on Linux even though I have them in my PATH

### ISSUE THREAD

**Issue by roxwize** [KiwifruitDev/NonsensicalVideoGenerator#6]
### Release

Steam Release

### Version

1.0.0.21

### Platform

Linux

### Severity

Critical

### Description

I run OpenSUSE Tumbleweed (v20231226), it comes with ffmpeg and ffprobe preinstalled. I tried installing the program and running it via Proton Experimental and it seems to work perfectly fine so far but it's not detecting either of said programs. I don't have them in NVG's folder, but I have them in /usr/bin which is included in my $PATH variable. I'm assuming this is a problem with the application running over Proton.

```sh
~> ffmpeg -version
ffmpeg version 6.0.1 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13 (SUSE Linux)
# rest of output truncated
~> ffprobe -version
ffprobe version 6.0.1 Copyright (c) 2007-2023 the FFmpeg developers
built with gcc 13 (SUSE Linux)
# rest of output truncated
```

Additionally, I have ImageMagick preinstalled on my system as well, which does not seem to be detected either (if it is what "Magick" is referring to).

### Proton Version

- [x] Ge-Proton7-30
- [X] Proton Experimental
- [ ] Proton 8.0-3
- [ ] Proton 7.0-6
- [ ] Proton 6.3-8
- [ ] Proton 5.13-6
- [ ] Proton 5.0-10
- [ ] Proton 4.11-13
- [ ] Proton 4.2-9
- [ ] Proton 3.16-9
- [ ] Proton 3.7-8
- [X] Proton Hotfix

**Comment by KiwifruitDev** [comment]
NVG does not support Linux natively. Proton GE is the best way to use it, however there are some issues related to Steam Workshop when using Proton. These were fixed by creating a DesktopGL build, which is better supported when using Proton but still isn't native Linux. I may start releasing DesktopGL builds again, as I only stopped due to lack of usage.

**Comment by roxwize** [comment]
Using both GE-Proton7-30 and GE-Proton8-25 with NVG didn't seem to fix the problem either. DesktopGL builds would be fine but I'm personally fine with just using Windows with the software if the usage was small enough to warrant its prior removal.

**Comment by accidentalcoincidence** [comment]
same issue here, i don't have a windows pc so i'd appreciate a more compatible build for linux but i understand if that's too much effort

**Comment by rexendevar** [comment]
I was unable to get NVG to accept imagemagick even though I installed it into the Steam prefix with a windows installer. I discovered that  NVG is running with command option `-nopath`. might be the same problem idk - i still don't know how to get imagemagick to function.

**Comment by KiwifruitDev** [comment]
NVG is not planned to support Linux due to increasing issues with Proton and MonoGame's general lackluster support for it.
