### ISSUE TITLE
Linux: short pause between every clip

### ISSUE THREAD

**Issue by rexendevar** [KiwifruitDev/NonsensicalVideoGenerator#7]
### Release

Steam Release

### Version

1.0.0.25

### Platform

Linux

### Severity

Minor

### Description

Upon rendering any output video, there will be a pause of about a quarter second in between each clip.

https://github.com/KiwifruitDev/NonsensicalVideoGenerator/assets/46948713/c0cac90f-4412-4795-ab85-7c0e02841b47

### Reproduction Steps

Install on Steam on Linux. Download ffmpeg via the button within NVG.

Import a bunch of clips (I exclusively put them in materials) and render a video. 

### Expected Behavior

Each clip will be directly one after another with the standard breakneck adhd editing style.

### Actual Behavior

Each clip pauses for several frames silently before going to the next one.

### Console Log

https://cdn.discordapp.com/attachments/916005268310073365/1245109739722117141/console.txt?ex=66578e4e&is=66563cce&hm=36a2ea08be4aa76322db08aa4914fc0f755ffec735e7f5f09f8e919dd4e9c2ce&

### Options Save File

https://pastebin.com/qYLWi87R

### User Consents

I could not find this file.

### Proton Version

- [ ] Ge-Proton7-30
- [X] Proton Experimental
- [ ] Proton 8.0-3
- [ ] Proton 7.0-6
- [ ] Proton 6.3-8
- [ ] Proton 5.13-6
- [ ] Proton 5.0-10
- [ ] Proton 4.11-13
- [ ] Proton 4.2-9
- [ ] Proton 3.16-9
- [ ] Proton 3.7-8
- [ ] Proton Hotfix

**Comment by KiwifruitDev** [comment]
NVG is not planned to support Linux due to increasing issues with Proton and MonoGame's general lackluster support for it.

**Comment by rexendevar** [comment]
I don't remember what changes I made but I can confirm that this issue is gone and NVG currently works fine with Proton for me.
