### ISSUE TITLE
Filter button lacks translation keys

### ISSUE THREAD

**Issue by RLH-2110** [KiwifruitDev/NonsensicalVideoGenerator#9]
### Release

Steam Release

### Version

1.0.11

### Platform

Windows

### Severity

Cosmetic

### Description

The filter button in the add-on management screen has only this translation key: "Interactable:FilterTitle": "Filter: %1",
the filters in %1 seem to be hardcoded.

### Reproduction Steps

Use a complete translation file and go to the add-on management screen

### Expected Behavior

There should be translation keys for the filters and it should be translated

### Actual Behavior

Translation keys don't seem to exist.

### Proton Version

- [ ] Ge-Proton7-30
- [ ] Proton Experimental
- [ ] Proton 8.0-3
- [ ] Proton 7.0-6
- [ ] Proton 6.3-8
- [ ] Proton 5.13-6
- [ ] Proton 5.0-10
- [ ] Proton 4.11-13
- [ ] Proton 4.2-9
- [ ] Proton 3.16-9
- [ ] Proton 3.7-8
- [ ] Proton Hotfix

**Comment by KiwifruitDev** [comment]
Fixed with f9fefa8 ([v1.0.1.2](https://store.steampowered.com/news/app/2516360/view/4250916799096006721)).
